development: &defaults
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: secret
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: backend_development

test:
  <<: *defaults
  database: backend_test

staging:
  <<: *defaults
  database: backend_staging

production:
  <<: *defaults
  database: backend_production
