version: '2'

services:
  nginx:
    image: bitnami/nginx:1.10.2-r1
    volumes:
      - ./config/nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - backend
      - frontend
    environment:
      VIRTUAL_HOST: sms-challenge.docker
      VIRTUAL_PORT: 8080
    ports:
      - 8080:8080
  db:
    image: postgres:9.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      ALLOW_IP_RANGE: 0.0.0.0/0
  backend:
    build: backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - '3000:3000'
  frontend:
    build:
      context: ./frontend/
    depends_on:
      - backend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/frontend
      - ./frontend/node_modules:/usr/src/frontend/node_modules
    ports:
      - '4000:4000'
