source 'https://rubygems.org'
ruby '2.5.3'

gem 'rails', '~> 5.1.7'
gem 'rack-cors', require: 'rack/cors'
gem 'pg'

gem 'spring', group: :development

group :development, :test do
  gem 'pry'
  gem 'rspec-rails'
end

group :test do
  gem 'database_rewinder'
end
