source 'https://rubygems.org'
ruby '2.4.0'

gem 'rails'
gem 'rack-cors', require: 'rack/cors'

gem 'pg'

gem 'spring', group: :development

group :development, :test do
  gem "pry"
  gem "rspec-rails"
  gem "factory_bot", "~> 4.0"
end
